#!/usr/bin/env python3

from nodex import Nodex
from nodex import Graph
import names

edgeWeight = 16.0
nextNodeID = 0
finalHomeNode = 0
numDropped = 0

graph = Graph("gen_graph")

from optparse import OptionParser

usage = "usage: %prog [options] arg"
parser = OptionParser(usage)
parser.add_option("-f", "--file", dest="filename", help="read data from FILENAME")
parser.add_option("-n", "--nodes", dest="numNodes", help="number of nodes in graph")
parser.add_option("-s", "--homes", dest="numHomes", help="number of homes")
parser.add_option("-x", "--start", dest="dijkStart", help="dijkStart")

(options, args) = parser.parse_args()


for i in range(int(options.numNodes)):
    if graph.nodeCount >= int(options.numNodes):
        break
    parentNode = Nodex(names.get_first_name() + str(nextNodeID), nextNodeID)
    nextNodeID+=1
    graph.addRouteNode(parentNode)
    if i != 0:
        lastNode.addNeighbor(parentNode)
        parentNode.addNeighbor(lastNode)
    lastNode = parentNode
    graph.addNode(parentNode)
    if graph.nodeCount >= int(options.numNodes):
        break
    if i % 5 == 0:
        if numDropped < int(options.numHomes):
            graph.droppedAt[parentNode.name] = []
        for j in range(4):
            node = Nodex(names.get_first_name() + str(nextNodeID) , nextNodeID)
            nextNodeID += 1
            if numDropped < int(options.numHomes):
                graph.droppedAt[parentNode.name].append(node.name)
                numDropped+=1
            graph.setHomeNode(node, int(options.numHomes))
            graph.addNodeNeighbors(node, parentNode)
            if graph.nodeCount >= int(options.numNodes):
                break
    elif i % 5 == 1:
        current = parentNode
        localRoute = []
        localRoute.append(parentNode.name)
        for j in range(3):
            node = Nodex(names.get_first_name() + str(nextNodeID), nextNodeID)
            if numDropped < int(options.numHomes):
                graph.droppedAt[node.name] = []
                graph.droppedAt[node.name].append(node.name)
                numDropped+=1
            nextNodeID += 1
            graph.setHomeNode(node, int(options.numHomes))
            
            if graph.foundHome != True:
                localRoute.append(node.name)
            if j != 2:
                graph.addRouteNode(node)
            graph.addNodeNeighbors(node, current)
            current = node
            if graph.nodeCount >= int(options.numNodes):
                break
        localRoute.reverse() 
        graph.newTotalRoute += localRoute
    elif i % 5 == 2:
        current = parentNode
        for j in range(2):
            node = Nodex(names.get_first_name() + str(nextNodeID), nextNodeID)
            nextNodeID += 1
            graph.setHomeNode(node, int(options.numHomes))
            if j == 0:
                graph.addRouteNode(node)
                graph.addRouteNode(parentNode)
                if numDropped < int(options.numHomes):
                    graph.droppedAt[node.name] = []
                    graph.droppedAt[node.name].append(node.name)
                    numDropped+=1
                prevName = node.name
            if j == 1:
                if numDropped < int(options.numHomes):
                    graph.droppedAt[prevName].append(node.name)
            graph.addNodeNeighbors(node, current)
            current = node
            if graph.nodeCount >= int(options.numNodes):
                break
    elif i % 5 == 3:
        node = Nodex(names.get_first_name() + str(nextNodeID), nextNodeID)
        nextNodeID += 1
        if numDropped < int(options.numHomes):
            graph.droppedAt[parentNode.name] = []
            graph.droppedAt[parentNode.name].append(node.name)
            numDropped+=1
        graph.setHomeNode(node, int(options.numHomes))
        graph.addNodeNeighbors(node, parentNode)
    else:
        current = parentNode
        dropName = ""
        for j in range(2):
            node = Nodex(names.get_first_name() + str(nextNodeID), nextNodeID)
            nextNodeID += 1
            if j == 0:
                graph.addRouteNode(node)
                graph.addRouteNode(parentNode)
                if numDropped < int(options.numHomes):
                    graph.droppedAt[node.name] = []
                    numDropped+=1
                dropName = node.name
            graph.addNodeNeighbors(node, current)
            current = node
            if graph.nodeCount >= int(options.numNodes):
                break
        for j in range(2):
            node = Nodex(names.get_first_name() + str(nextNodeID), nextNodeID)
            nextNodeID += 1
            if numDropped < int(options.numHomes):
                graph.droppedAt[dropName].append(node.name)
                numDropped+=1
            graph.setHomeNode(node, int(options.numHomes))
            graph.addNodeNeighbors(node, current)
            if graph.nodeCount >= int(options.numNodes):
                break

graph.newTotalRoute = graph.newTotalRoute[:-2]
graph.writeInputFile(options.filename)
graph.dijkstra(int(options.dijkStart),0)
graph.totalRoute = graph.newTotalRoute + graph.dijkstraRoute

print(graph.totalRoute)
print(f'fixed route{graph.newTotalRoute}')

graph.writeOutputFile(options.filename)

for k, v in graph.droppedAt.items():
    print(f'{k}:{v}\n')